name: 'Composer Rich Diff Action'
description: 'Creates a readable diff of any changes made to Composer requirements and/or locked packages.'
author: 'Chris Smith'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
  path:
    description: 'Path to the composer.json file you wish to analyse for changes.'
    default: 'composer.json'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
